title: Hablando en data
description: Recopilatorio de contenido útil sobre Ciencia de datos
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Abilio Romero e Ivan Robles
repo_url: "https://github.com/hablandoendata/WebRecopilatorio"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
